FROM node:22-alpine AS build
WORKDIR /web
ARG VITE_SITE_NAME=ShitIDC
ARG VITE_SITE_LOGO_URL=
ENV VITE_SITE_NAME=${VITE_SITE_NAME}
ENV VITE_SITE_LOGO_URL=${VITE_SITE_LOGO_URL}
COPY web/package*.json ./
RUN npm install
COPY web .
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /web/dist /usr/share/nginx/html
COPY themes /usr/share/nginx/html/themes
